# containers
services:
  fruithub-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruithub-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - fruithub-network
        
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fruithub-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - fruithub-network
    healthcheck:
      test: >
        /opt/mssql-tools18/bin/sqlcmd
        -S localhost
        -U sa
        -P "$$MSSQL_SA_PASSWORD"
        -C
        -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  fruithub-network:
    driver: bridge

volumes:
  sqlserver-data:
